### ISSUE TITLE
about three-way classification

### ISSUE THREAD

**Issue by payphone131** [ydyjya/LLM-IHS-Explanation#1]
hello, your work is really interesting to me and i want to reproduce some results. if i want to train a three-way classifier, should i directly change`test.explain({"norm":normal, "mali":malicious}, classifier_list=["svm", "mlp"], accuracy=True)`  to `est.explain({"norm":normal, "mali":malicious, "jail":jailbreak}, classifier_list=["svm", "mlp"], accuracy=True)` in example.ipynb?

**Comment by ydyjya** [comment]
😊 Hi, if you want to conduct a three-way experiments, your modification is right. Nevertheless, you might reproduce some jailbreak results for classification.

**Comment by payphone131** [comment]
thanks, your reply really helps.
